#!/bin/bash
# K3s Multi-Node Cluster Setup
# This script sets up a production-ready K3s cluster with 2 nodes

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}K3s Multi-Node Cluster Setup Guide${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

echo -e "${YELLOW}Prerequisites:${NC}"
echo -e "1. Two physical machines with Ubuntu/Debian/RHEL"
echo -e "2. SSH access to both machines"
echo -e "3. Root/sudo access on both machines"
echo -e "4. Machines can communicate with each other"
echo ""

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Node 1 (Control Plane) Setup${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo -e "${YELLOW}On your first machine (control plane + worker):${NC}"
echo ""
echo -e "${GREEN}# Install K3s server${NC}"
echo -e "curl -sfL https://get.k3s.io | sh -s - server \\"
echo -e "  --disable traefik \\"
echo -e "  --disable servicelb \\"
echo -e "  --write-kubeconfig-mode 644 \\"
echo -e "  --node-name shamel"
echo ""
echo -e "${GREEN}# Wait for K3s to be ready${NC}"
echo -e "sudo systemctl status k3s"
echo ""
echo -e "${GREEN}# Get the node token (needed for worker nodes)${NC}"
echo -e "sudo cat /var/lib/rancher/k3s/server/node-token"
echo ""
echo -e "${YELLOW}Copy the token output - you'll need it for Node 2!${NC}"
echo ""
echo -e "${GREEN}# Get the server IP${NC}"
echo -e "hostname -I | awk '{print \$1}'"
echo ""
echo -e "${YELLOW}Copy the IP address - you'll need it for Node 2!${NC}"
echo ""

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Node 2 (Worker) Setup${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo -e "${YELLOW}On your second machine (WiFi capture node):${NC}"
echo ""
echo -e "${GREEN}# Install K3s agent${NC}"
echo -e "# Replace <SERVER_IP> with Node 1's IP"
echo -e "# Replace <NODE_TOKEN> with the token from Node 1"
echo ""
echo -e "curl -sfL https://get.k3s.io | K3S_URL=https://<SERVER_IP>:6443 \\"
echo -e "  K3S_TOKEN=<NODE_TOKEN> \\"
echo -e "  sh -s - agent \\"
echo -e "  --node-name shamel-m02"
echo ""
echo -e "${GREEN}# Wait for agent to be ready${NC}"
echo -e "sudo systemctl status k3s-agent"
echo ""

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Verify Cluster (on Node 1)${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo -e "${GREEN}# Check nodes${NC}"
echo -e "kubectl get nodes"
echo ""
echo -e "${YELLOW}You should see:${NC}"
echo -e "NAME          STATUS   ROLES                  AGE   VERSION"
echo -e "shamel        Ready    control-plane,master   1m    v1.28.x+k3s1"
echo -e "shamel-m02    Ready    <none>                 30s   v1.28.x+k3s1"
echo ""

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Install Required Components${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo -e "${GREEN}# Install Helm (on Node 1)${NC}"
echo -e "curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash"
echo ""
echo -e "${GREEN}# Install NGINX Ingress Controller${NC}"
echo -e "kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.0/deploy/static/provider/baremetal/deploy.yaml"
echo ""
echo -e "${GREEN}# Wait for ingress to be ready${NC}"
echo -e "kubectl wait --namespace ingress-nginx \\"
echo -e "  --for=condition=ready pod \\"
echo -e "  --selector=app.kubernetes.io/component=controller \\"
echo -e "  --timeout=120s"
echo ""

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Install Strimzi Kafka Operator${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo -e "${GREEN}# Create kafka namespace${NC}"
echo -e "kubectl create namespace kafka"
echo ""
echo -e "${GREEN}# Install Strimzi operator${NC}"
echo -e "helm install strimzi-kafka oci://quay.io/strimzi-helm/strimzi-kafka-operator -n kafka"
echo ""
echo -e "${GREEN}# Wait for operator${NC}"
echo -e "kubectl wait --for=condition=ready pod -l name=strimzi-cluster-operator -n kafka --timeout=300s"
echo ""
echo -e "${GREEN}# Deploy Kafka cluster${NC}"
echo -e "kubectl apply -f kafka-cluster.yaml"
echo ""

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Install Flink Operator${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo -e "${GREEN}# Install Flink operator${NC}"
echo -e "kubectl create -f https://github.com/apache/flink-kubernetes-operator/releases/download/release-1.10.0/flink-kubernetes-operator-1.10.0.yaml"
echo ""
echo -e "${GREEN}# Wait for operator${NC}"
echo -e "kubectl wait --for=condition=ready pod \\"
echo -e "  -l app.kubernetes.io/name=flink-kubernetes-operator \\"
echo -e "  -n flink-kubernetes-operator \\"
echo -e "  --timeout=300s"
echo ""

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Deploy Your Applications${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo -e "${GREEN}# Deploy infrastructure${NC}"
echo -e "helm install shamelv2 ./helm-chart"
echo ""
echo -e "${GREEN}# Deploy Flink job${NC}"
echo -e "helm install flink-job ./flink-job-chart"
echo ""

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Access Configuration${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo -e "${GREEN}# Setup kubectl on your laptop (copy from Node 1)${NC}"
echo -e "scp root@<NODE1_IP>:/etc/rancher/k3s/k3s.yaml ~/.kube/k3s-config"
echo -e "# Edit the file and change 127.0.0.1 to your Node 1's IP"
echo -e "export KUBECONFIG=~/.kube/k3s-config"
echo -e "kubectl get nodes"
echo ""

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Useful Commands${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo -e "${GREEN}# Uninstall K3s (Node 1)${NC}"
echo -e "sudo /usr/local/bin/k3s-uninstall.sh"
echo ""
echo -e "${GREEN}# Uninstall K3s (Node 2)${NC}"
echo -e "sudo /usr/local/bin/k3s-agent-uninstall.sh"
echo ""
echo -e "${GREEN}# View K3s logs (Node 1)${NC}"
echo -e "sudo journalctl -u k3s -f"
echo ""
echo -e "${GREEN}# View K3s agent logs (Node 2)${NC}"
echo -e "sudo journalctl -u k3s-agent -f"
echo ""

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}Setup Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo -e "${YELLOW}Important Notes:${NC}"
echo -e "• K3s uses /etc/rancher/k3s/k3s.yaml for kubeconfig"
echo -e "• Default storage class: local-path"
echo -e "• Your apps will use CSI storage (already configured)"
echo -e "• Node 1 (shamel): All services + Kafka + Flink"
echo -e "• Node 2 (shamel-m02): WiFi packet capture"
echo ""
