
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-svc
spec:
  selector:
    app: clickhouse
  ports:
    - protocol: TCP
      port: 8123
      name: chtcp1
      targetPort: 8123
    - protocol: TCP
      port: 9000
      name: chtcp2
      targetPort: 9000
  type: ClusterIP
