apiVersion: v1
kind: Namespace
metadata:
  name: llm-serving
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama3-models-pvc
  namespace: llm-serving
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama3-vllm
  namespace: llm-serving
  labels:
    app: llama3-vllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama3-vllm
  template:
    metadata:
      labels:
        app: llama3-vllm
    spec:
      nodeSelector:
        kubernetes.io/hostname: ai-worker
      containers:
      - name: vllm
        image: vllm/vllm-openai:v0.6.3.post1
        command:
          - python3
          - -m
          - vllm.entrypoints.openai.api_server
          - --model
          - meta-llama/Meta-Llama-3-8B-Instruct
          - --dtype
          - float16
          - --max-model-len
          - "4096"
          - --gpu-memory-utilization
          - "0.85"
          - --port
          - "8000"
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        env:
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: huggingface-token
              key: token
              optional: true
        resources:
          requests:
            cpu: "4"
            memory: "16Gi"
            nvidia.com/gpu: "1"
          limits:
            nvidia.com/gpu: "1"
        volumeMounts:
        - name: cache
          mountPath: /root/.cache/huggingface
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 300
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: cache
        persistentVolumeClaim:
          claimName: llama3-models-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: llama3-service
  namespace: llm-serving
  labels:
    app: llama3-vllm
spec:
  type: ClusterIP
  selector:
    app: llama3-vllm
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
---
# Optional: Secret for HuggingFace token (if needed for gated models)
# Create with: kubectl create secret generic huggingface-token --from-literal=token=YOUR_TOKEN -n llm-serving
apiVersion: v1
kind: Secret
metadata:
  name: huggingface-token
  namespace: llm-serving
type: Opaque
stringData:
  token: ""
