apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama3-vllm
  namespace: default
  labels:
    app: llm-serving
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-serving
  template:
    metadata:
      labels:
        app: llm-serving
    spec:
      nodeSelector:
        kubernetes.io/hostname: ai-worker
      containers:
      - name: vllm
        image: vllm/vllm-openai:latest
        imagePullPolicy: IfNotPresent
        command:
        - python3
        - -m
        - vllm.entrypoints.openai.api_server
        - --model
        - meta-llama/Meta-Llama-3-8B-Instruct
        - --host
        - "0.0.0.0"
        - --port
        - "8000"
        - --dtype
        - float16
        - --max-model-len
        - "4096"
        - --gpu-memory-utilization
        - "0.9"
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: HF_HOME
          value: "/data/huggingface"
        - name: TRANSFORMERS_CACHE
          value: "/data/huggingface"
        volumeMounts:
        - name: model-cache
          mountPath: /data/huggingface
        resources:
          requests:
            nvidia.com/gpu: 1
            cpu: "4"
            memory: "16Gi"
          limits:
            nvidia.com/gpu: 1
            cpu: "8"
            memory: "24Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 300
          periodSeconds: 60
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 300
          periodSeconds: 30
          timeoutSeconds: 10
      volumes:
      - name: model-cache
        hostPath:
          path: /data/huggingface
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: llama3-service
  namespace: default
  labels:
    app: llm-serving
spec:
  type: ClusterIP
  selector:
    app: llm-serving
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
