apiVersion: v1
kind: Service
metadata:
  name: wifi-stats-backend-svc
  labels:
    app: wifi-stats-backend
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: wifi-stats-backend
