apiVersion: apps/v1
kind: Deployment
metadata:
  name: wifi-stats-ai-agent
  labels:
    app: wifi-stats-ai-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wifi-stats-ai-agent
  template:
    metadata:
      labels:
        app: wifi-stats-ai-agent
    spec:
      nodeSelector:
        kubernetes.io/hostname: ai-worker
      containers:
      - name: ai-agent
        image: docker.io/library/wifi-stats-ai-agent:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: LLM_SERVICE_URL
          value: "http://llama3-service.default.svc.cluster.local:8000/v1/completions"
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: wifi-stats-ai-agent-svc
  labels:
    app: wifi-stats-ai-agent
spec:
  type: ClusterIP
  selector:
    app: wifi-stats-ai-agent
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
